<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Project Cards</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      display: flex;
      justify-content: center;
      padding: 20px;
      background-color: #f0f0f0;
    }

    .container {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 20px;
      max-width: 1000px;
      width: 100%;
    }

    .card {
      background-color: white;
      padding: 15px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      transition: background-color 0.3s;
      cursor: pointer;
    }

    .card img {
      width: 100%;
      border-radius: 6px;
      height: 150px;
      object-fit: cover;
      margin-bottom: 10px;
    }

    .card:hover {
      background-color: lightgray;
    }

    .card h3 {
      margin: 0 0 8px;
    }

    .card p {
      margin: 0;
      color: #333;
    }
  </style>
</head>
<body>

  <div class="container" id="projectContainer">
    <!-- Cards will be generated by JavaScript -->
  </div>

  <script>
    const projects = [
      {
        title: "Project One",
        description: "This is the first project description.",
        image: "https://images.unsplash.com/photo-1494697536454-6f39e2cc972d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTB8fGNhcnxlbnwwfHwwfHx8MA%3D%3D"
      },
      {
        title: "Project Two",
        description: "This is the second project description.",
        image: "https://images.unsplash.com/photo-1494697536454-6f39e2cc972d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTB8fGNhcnxlbnwwfHwwfHx8MA%3D%3D"
      },
      {
        title: "Project Three",
        description: "This is the third project description.",
        image: "https://images.unsplash.com/photo-1494697536454-6f39e2cc972d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTB8fGNhcnxlbnwwfHwwfHx8MA%3D%3D"
      },
      {
        title: "Project Four",
        description: "This is the fourth project description.",
        image: "https://images.unsplash.com/photo-1494697536454-6f39e2cc972d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTB8fGNhcnxlbnwwfHwwfHx8MA%3D%3D"
      }
    ];

    const container = document.getElementById('projectContainer');

    projects.forEach(project => {
      const card = document.createElement('div');
      card.className = 'card';
      card.innerHTML = `
        <img src="${project.image}" alt="${project.title}">
        <h3>${project.title}</h3>
        <p>${project.description}</p>
      `;

      card.addEventListener('click', () => {
        alert(`${project.title}\n\n${project.description}`);
        card.style.backgroundColor = '#d0e6ff'; // Change background after click
      });

      container.appendChild(card);
    });
  </script>

</body>
</html>